version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: acme-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dev-database
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-password
    volumes:
     #  - ./db/seed.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql