packages:
  - apps/*
  - packages/*
  - packages/auth
  - packages/database
  - packages/mail
  - packages/config/eslint-config-custom
  - packages/config/tsconfig
  - packages/config/tailwind
  - packages/utils
